version: "3.8"

services:
  nginx-port1:
    image: nginx:alpine
    container_name: nginx-port1
    ports:
      - protocol: tcp
        published: 8080
        target: 80
  nginx-port2:
    image: nginx:alpine
    container_name: nginx-port2
    ports:
      - "8081:80"